name: halimau_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  supabase_flutter: ^2.9.1
  file_picker: ^6.1.1 
  universal_platform: ^1.0.0+1
  image_picker: ^1.1.2
  path: ^1.8.3
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/image.png
    - assets/pngwing.com (4).png
    - assets/rollertee.webp
